trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- bash: |
    set -e

    TERRAFORM_VERSION="1.9.8"

    wget -q "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"

    unzip -o "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"

    sudo mv terraform /usr/local/bin/terraform

    terraform version
  displayName: 'Install and Check Terraform'

 - bash: |
    terraform init
    terraform plan
  displayName: 'Terraform Init and Plan'

- task: AzureCLI@2
  displayName: 'Terraform Init and Validate'
  inputs:
    azureSubscription: 'Terraform-Azure-Connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform init
      terraform validate

- task: AzureCLI@2
  displayName: 'Terraform Plan'
  inputs:
    azureSubscription: 'Terraform-Azure-Connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform plan -out=tfplan

- task: AzureCLI@2
  displayName: 'Terraform Apply'
  inputs:
    azureSubscription: 'Terraform-Azure-Connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform apply -auto-approve tfplan